# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170218_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('Fa', 'Family'), ('Fr', 'Friendship'), ('Ha', 'Happiness'), ('Hu', 'Humor'), ('Li', 'Life'), ('Su', 'Success'), ('Wi', 'Wisdom')], default='Li', max_length=2),
        ),
    ]
